#!/usr/bin/env python3
"""Generates the Runner's ducked frames from its run frames.

    python3 tools/runner_duck_sprite.py   # writes assets/duck1.png, duck2.png
                                          # and assets/runner_duck.h (needs Pillow)

The runner (Platform Flux) ducks on B under Night's low obstacles. Its two
18x12 ducked frames are the 18x20 run frames squashed: the head and
shoulders kept and leant forward 2px, the body and legs taken a row in two
or three. Frame 2's legs come from run frame 2, so the duck shuffles as it
runs; anything left of column 3 below the head is dropped (run frame 2's
trailing arm, which squashed into a stray stick).

To draw them by hand instead: edit duck1.png/duck2.png (18x12, RGBA,
transparent background) and run with --from-png to convert just those.
Transparent pixels are written as RUNNER_TRANSPARENT_KEY (0x0001), as in
runner_sprites.h.
"""
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, '..', 'src', 'games', 'PlatformFlux', 'assets')
W, H = 18, 12
LEAN = 2                     # head and shoulders forward, px
HEAD_ROWS = 7                # rows that lean
ROWS = [0, 1, 2, 3, 4, 5, 6, 10, 13, 16, 18, 19]   # run-frame rows kept, top to bottom
LEG_FROM = 9                 # ducked rows from here are legs (frame 2 uses its own)
KEY = 0x0001


def squash(body, legs):
    out = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    for oy, sy in enumerate(ROWS):
        src = legs if oy >= LEG_FROM else body
        dx = LEAN if oy < HEAD_ROWS else 0
        for x in range(W):
            px = src.getpixel((x, sy))
            if px[3] == 0:
                continue
            nx = x + dx
            if oy >= HEAD_ROWS and nx < 3:
                continue
            if 0 <= nx < W:
                out.putpixel((nx, oy), px)
    return out


def rgb565(px):
    r, g, b, a = px
    if a == 0:
        return KEY
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return 0x0020 if v == KEY else v     # never the key by accident


def header(frames):
    lines = [
        '#ifndef RUNNER_DUCK_H',
        '#define RUNNER_DUCK_H',
        '',
        '#include <Arduino.h>',
        '',
        '// Generated by tools/runner_duck_sprite.py from duck1.png/duck2.png',
        '// (18x12): the runner ducked, two frames. Transparent pixels are',
        '// RUNNER_TRANSPARENT_KEY, as in runner_sprites.h.',
        'static const int RUNNER_DUCK_WIDTH  = %d;' % W,
        'static const int RUNNER_DUCK_HEIGHT = %d;' % H,
        '',
    ]
    for n, im in enumerate(frames, 1):
        lines.append('static const uint16_t runner_frame_duck%d[%d] PROGMEM = {' % (n, W * H))
        for y in range(H):
            row = ', '.join('0x%04X' % rgb565(im.getpixel((x, y))) for x in range(W))
            lines.append('    %s,' % row)
        lines.append('};')
        lines.append('')
    lines.append('#endif // RUNNER_DUCK_H')
    return '\n'.join(lines) + '\n'


def main():
    p1, p2 = os.path.join(ASSETS, 'duck1.png'), os.path.join(ASSETS, 'duck2.png')
    if '--from-png' in sys.argv:
        frames = [Image.open(p).convert('RGBA') for p in (p1, p2)]
    else:
        run1 = Image.open(os.path.join(ASSETS, 'frame1.png')).convert('RGBA')
        run2 = Image.open(os.path.join(ASSETS, 'frame2.png')).convert('RGBA')
        frames = [squash(run1, run1), squash(run1, run2)]
        frames[0].save(p1)
        frames[1].save(p2)
    for im in frames:
        assert im.size == (W, H), 'ducked frames are %dx%d' % (W, H)
    with open(os.path.join(ASSETS, 'runner_duck.h'), 'w') as f:
        f.write(header(frames))
    print('wrote runner_duck.h')


if __name__ == '__main__':
    main()
