#!/usr/bin/env python3
"""Renders Star Flux's ship sprite frames and writes them as an RGB565 header.

    python3 tools/star_ship_sprite.py            # write the header
    python3 tools/star_ship_sprite.py --preview  # also star_ship_preview.png

Needs numpy (and Pillow for the preview). The ship is the 3D model in
tools/star_ship_model.py, rendered from behind and a little above - where
the game's camera is - at 8x resolution, then reduced: a pixel is solid if
the ship covers most of it, coloured by the average of what covers it, and
the silhouette gets a one-pixel dark outline so it reads against space.

Three frames: level, banking, and banking hard (right wing down). The game
mirrors the bank frames with Sprite2D::FLIP_X for the left.

RGB565 0x0000 is the colour key, so no pixel may be pure black.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from star_ship_model import Camera, rasterise, rot_y, rot_z, ship_triangles, transform  # noqa: E402

W, H = 44, 38
SS = 8
OUTLINE = (26, 22, 44)
# (roll, yaw) per frame, degrees: roll right is right wing down.
FRAMES = [("SHIP_LEVEL", 0, 0), ("SHIP_BANK", -22, 7), ("SHIP_BANK_HARD", -44, 12)]


def render_frame(roll, yaw):
    tris = transform(ship_triangles(), rot_y(yaw) @ rot_z(roll))
    cam = Camera(pos=(0, 5.8, -10.5), target=(0, -0.45, 0.6), width=W * SS, height=H * SS, fov_deg=35)
    rgb = np.zeros((H * SS, W * SS, 3))
    depth = np.full((H * SS, W * SS), np.inf)
    cover = np.zeros((H * SS, W * SS), np.uint8)
    rasterise(tris, cam, rgb, depth, ambient=0.55, cover=cover)

    cov = cover.reshape(H, SS, W, SS).mean(axis=(1, 3))
    sums = (rgb * cover[..., None]).reshape(H, SS, W, SS, 3).sum(axis=(1, 3))
    cnt = cover.reshape(H, SS, W, SS).sum(axis=(1, 3))
    solid = cov >= 0.42
    out = np.zeros((H, W, 3))
    out[solid] = sums[solid] / cnt[solid][:, None]
    edge = np.zeros_like(solid)
    edge[1:, :] |= solid[:-1, :]
    edge[:-1, :] |= solid[1:, :]
    edge[:, 1:] |= solid[:, :-1]
    edge[:, :-1] |= solid[:, 1:]
    edge &= ~solid
    out[edge] = OUTLINE
    return out, solid | edge


def rgb565(c):
    r, g, b = (int(max(0, min(255, round(v)))) for v in c)
    v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return v if v else 0x0841   # never the colour key


def c_array(name, img, mask):
    vals = [rgb565(img[y, x]) if mask[y, x] else 0 for y in range(H) for x in range(W)]
    lines = ["    " + ", ".join(f"0x{v:04X}" for v in vals[y * W:(y + 1) * W]) + "," for y in range(H)]
    return f"inline const uint16_t {name}[SHIP_W * SHIP_H] = {{\n" + "\n".join(lines) + "\n};\n"


def main():
    frames = [(name,) + render_frame(roll, yaw) for name, roll, yaw in FRAMES]
    for name, _, mask in frames:
        if mask[0].any() or mask[-1].any() or mask[:, 0].any() or mask[:, -1].any():
            sys.exit(f"{name} touches the sprite's edge: widen W/H or pull the camera back")

    arrays = "\n".join(c_array(n, img, m) for n, img, m in frames)
    header = f"""#ifndef STAR_SHIP_SPRITE_H
#define STAR_SHIP_SPRITE_H

#include <stdint.h>

// Star Flux's ship, seen from behind and a little above: RGB565, {W}x{H},
// 0x0000 is the colour key (transparent), so the art never uses pure black.
//
// Three frames: level, banking right and banking hard right. Banking left
// draws the same frames with Sprite2D::FLIP_X.
//
// GENERATED by tools/star_ship_sprite.py from the 3D model in
// tools/star_ship_model.py - change it there and re-run; don't edit these.

namespace starflux {{

inline constexpr int SHIP_W = {W};
inline constexpr int SHIP_H = {H};

{arrays}
}}  // namespace starflux

#endif  // STAR_SHIP_SPRITE_H
"""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "src", "games", "StarFlux", "StarShipSprite.h")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write(header)
    print("wrote", out)

    if "--preview" in sys.argv:
        from PIL import Image
        scale = 8
        img = Image.new("RGB", ((W + 2) * scale * len(frames), H * scale), (8, 10, 30))
        for i, (_, rgb, mask) in enumerate(frames):
            for y in range(H):
                for x in range(W):
                    if mask[y, x]:
                        c = tuple(int(max(0, min(255, v))) for v in rgb[y, x])
                        img.paste(c, (i * (W + 2) * scale + x * scale, y * scale,
                                      i * (W + 2) * scale + (x + 1) * scale, (y + 1) * scale))
        img.save("star_ship_preview.png")
        print("wrote star_ship_preview.png")


if __name__ == "__main__":
    main()
