#!/usr/bin/env python3
"""Generates src/games/TubeFlux/TubeShipSprite.h from the pixel art below.

    python3 tools/tube_ship_sprite.py            # write the header
    python3 tools/tube_ship_sprite.py --preview  # also ship_preview.png (needs Pillow)

Edit the art here, not the header. One character per pixel; '.' is
transparent. The ship is drawn as its left half and mirrored, so it stays
symmetric. The bank frame is the level frame sheared (right wing down);
the game mirrors it with Sprite2D::FLIP_X for the left bank.

RGB565 0x0000 is the sprite's colour key, so no palette entry may be pure
black: the darkest colour is the navy outline.
"""
import os
import sys

PALETTE = {
    '.': None,
    'K': (22, 28, 58),     # outline
    'W': (232, 240, 255),  # highlight
    'L': (150, 172, 214),  # light hull
    'M': (88, 108, 168),   # mid hull
    'D': (50, 62, 108),    # dark hull
    'C': (70, 230, 255),   # canopy
    'c': (20, 120, 160),   # canopy shade
    'R': (255, 48, 64),    # wingtip
    'O': (255, 140, 30),   # engine
    'Y': (255, 245, 110),  # engine core
}

LEFT_HALF = [
    "................",
    "........K.......",
    "........KK......",
    "........KMK..KKK",
    "........KDMKKcCW",
    "........KDMKcCCC",
    "........KKDLLccc",
    "......KKDMMLLLLW",
    ".....KDMMMLLLLLL",
    "...KKDMMMLLLLLLL",
    ".KKDMMLLLLLMMLLL",
    "KRLLLLLLLMMDDMML",
    ".KRDDDDDDDDKDMML",
    "..KKKKKKKKKOOKDD",
    "..........KOYYOK",
    "..........KOYYOK",
    "...........KOOK.",
]

W, H = 32, 20
BANK_SHEAR = 0.14   # pixels of vertical shift per pixel from the centre


def level_frame():
    rows = [r + r[::-1] for r in LEFT_HALF]
    # Padding above and below leaves room for the bank frame's shear.
    top = (H - len(rows)) // 2
    return ["." * W] * top + rows + ["." * W] * (H - top - len(rows))


def bank_frame(level):
    out = [["."] * W for _ in range(H)]
    for x in range(W):
        dy = round((x - (W / 2 - 0.5)) * BANK_SHEAR)
        for y in range(H):
            ny = y + dy
            if 0 <= ny < H and level[y][x] != ".":
                out[ny][x] = level[y][x]
    return ["".join(r) for r in out]


def rgb565(c):
    r, g, b = c
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def c_array(name, rows):
    vals = [0 if PALETTE[ch] is None else rgb565(PALETTE[ch]) for r in rows for ch in r]
    lines = ["    " + ", ".join(f"0x{v:04X}" for v in vals[y * W:(y + 1) * W]) + ","
             for y in range(H)]
    return (f"inline const uint16_t {name}[SHIP_W * SHIP_H] = {{\n" +
            "\n".join(lines) + "\n};\n")


def main():
    for key, colour in PALETTE.items():
        if colour is not None and rgb565(colour) == 0:
            sys.exit(f"palette entry {key!r} is pure black in RGB565: that's the colour key")
    level = level_frame()
    bank = bank_frame(level)

    header = f"""#ifndef TUBE_SHIP_SPRITE_H
#define TUBE_SHIP_SPRITE_H

#include <stdint.h>

// Tube Flux's ship, seen from behind: RGB565, {W}x{H}, 0x0000 is the
// colour key (transparent), so the art never uses pure black - its darkest
// colour is the navy outline.
//
// Two frames. SHIP_BANK is the level frame sheared so the right wing dips
// (rolling right); rolling left draws the same frame with Sprite2D::FLIP_X.
//
// GENERATED by tools/tube_ship_sprite.py - edit the art there and re-run it.

namespace tubeflux {{

inline constexpr int SHIP_W = {W};
inline constexpr int SHIP_H = {H};

{c_array("SHIP_LEVEL", level)}
{c_array("SHIP_BANK", bank)}
}}  // namespace tubeflux

#endif  // TUBE_SHIP_SPRITE_H
"""
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "src", "games", "TubeFlux", "TubeShipSprite.h")
    with open(out, "w") as f:
        f.write(header)
    print("wrote", out)

    if "--preview" in sys.argv:
        from PIL import Image
        scale = 8
        img = Image.new("RGB", (W * scale * 2 + scale, H * scale), (0, 0, 0))
        for i, frame in enumerate((level, bank)):
            for y, row in enumerate(frame):
                for x, ch in enumerate(row):
                    if PALETTE[ch]:
                        for dy in range(scale):
                            for dx in range(scale):
                                img.putpixel((i * (W * scale + scale) + x * scale + dx, y * scale + dy),
                                             PALETTE[ch])
        img.save("ship_preview.png")
        print("wrote ship_preview.png")


if __name__ == "__main__":
    main()
